### ISSUE TITLE
Publish pigmnts-cli on crates.io

### ISSUE THREAD

**Issue by oknozor** [blenderskool/pigmnts#26]
Currently only the lib crate is available on crates.io can you please publish the cli to ?

**Comment by blenderskool** [comment]
Yes will publish it and add it to CI

**Comment by blenderskool** [comment]
@oknozor Pigmnts CLI has been published on crates.io - https://crates.io/crates/pigmnts-cli

It can be installed by running
```bash
cargo install pigmnts-cli
```
