### ISSUE TITLE
Add validation so that only allow images

### ISSUE THREAD

**Issue by VenomFate-619** [blenderskool/pigmnts#42]
Currently one can upload any file type, I think it should be restricted to only images
If I upload a pdf (any other type) the loader didn't stop.
![image](https://user-images.githubusercontent.com/67755128/178983046-e52947d2-6432-4492-bf41-f2c1906479a0.png)

I would like to fix this.

**Comment by blenderskool** [comment]
Good catch @VenomFate-619, I'll fix this asap, thanks for opening an issue.
[pigmnts.web.app](https://pigmnts.web.app) is not open source. This repository is only for the underlying pigmnts library which is open source.
